import type { Survivor } from '@/data'
import type { FiredRule } from '@/engine/survivorship/lateRules'

/**
 * The PCP handoff letter.
 *
 * Reproduced from the legacy app. Returns HTML because the letter is formatted
 * prose with emphasised test names — and it is authored here, from the app's own
 * data, so it renders through RichText rather than being escaped.
 */
export function buildLetter(s: Survivor, hits: FiredRule[]): string {
  const surv = hits.map((h) => `· <b>${h.hit.test}</b> — ${h.hit.freq}. ${h.hit.note}.`).join('<br>')
  return `Re: <b>${s.name}</b> (MRN ${s.mrn}) — Survivorship care plan · ${s.parish} Parish<br><br>
Dear Dr. _____,<br><br>
${s.name}, ${s.age}, completed treatment for <b>${s.dx}</b> in ${s.endDate.slice(-4)}. The survivorship care plan below is auto-generated by BayouCare from the treatment record (ASCO format) and reviewed at our survivorship clinic.<br><br>
<b>Active surveillance to maintain:</b><br>${surv}<br><br>
<b>Red flags to act on promptly:</b> fever ≥ 100.4°F; new chest pain, palpitations, or shortness of breath; new lumps or skin changes; arm swelling (lymphedema); unexplained weight loss.<br><br>
<b>Referrals available on request:</b> NAMI Louisiana / 988 for mood support · oncology rehabilitation &amp; lymphedema therapy · LA Quitline (1-800-QUIT-NOW) if smoking · genetic counseling where indicated.<br><br>
BayouCare AI draft — reviewed by Marie Thibodeaux, RN, survivorship navigator.`
}
