/* ============================================================================
   CLINICAL SAFETY — READ BEFORE EDITING

   The answer strings and triage regexes in this file are reproduced VERBATIM
   from the original single-file app, by a generator, not by hand. Do not
   "tidy" them, reflow them, or reformat the prose.

   The triage table is the safety property of this feature: it is evaluated
   BEFORE intent matching, so a message describing a crisis can never fall
   through to a cheerful answer about the appointment calendar. Reordering the
   loops in `remiAnswer` inverts that guarantee.

   Three tiers, in order:
     crisis   -> 988, and the care team is told
     urgent   -> call the care team now, or 911
     clinical -> routed to the care team, never answered

   A fourth outcome, `unknown`, means the question was not in the record. It
   says so. It does not guess.
   ========================================================================= */

export type TriageTier = 'crisis' | 'urgent' | 'clinical'

/** Evaluated top to bottom. Order IS the safety property. */
export const REMI_TRIAGE: Array<{ tier: TriageTier; rx: RegExp[] }> = [
  { tier:'crisis', rx:[
    /suicid/i, /kill myself/i, /killing myself/i, /end (it all|my life)/i, /want to die/i,
    /don'?t want to (be here|live)/i, /hurt myself/i, /self[- ]?harm/i, /better off dead/i,
    /no (point|reason) in (living|going on|being here)/i
  ]},
  { tier:'urgent', rx:[
    /chest pain/i, /\bchest\b[^.]{0,24}\b(tight|hurts?|pressure|heavy)\b/i,
    /can'?t breathe/i, /cannot breathe/i, /trouble breathing/i, /short(ness)? of breath/i,
    /heavy bleeding/i, /bleeding a lot/i, /won'?t stop bleeding/i,
    /\bfaint(ed|ing)?\b/i, /passed out/i, /unconscious/i, /seizure/i,
    /\bfever\b/i, /100\.4/, /\bchills\b/i
  ]},
  { tier:'clinical', rx:[
    /\bshould i (take|stop|skip|double|change)\b/i, /\bcan i take\b/i, /\bis it safe\b/i,
    /safe to take/i, /\bdos(e|age)\b/i,
    /\bhow much\b[^.]{0,30}\b(take|medicine|medication|mg|dose|painkiller)/i,
    /\bpainkillers?\b/i, /\bpain pills?\b/i,
    /oxycodone|ibuprofen|tylenol|advil|acetaminophen|morphine|opioid|chemo brain/i,
    /should i (worry|be worried|be concerned)/i, /am i going to die/i
  ]}
]

/** What each tier says. Routed answers are never generated by the model. */
export const REMI_ROUTED: Record<TriageTier, () => string> = {
  crisis(){ return `<b>Please reach out right now — you do not have to carry this alone.</b><br><br>` +
    `<b>988</b> — call or text. Free, 24/7, confidential. You can say anything.<br><br>` +
    `If you are in immediate danger, call <b>911</b>.<br><br>` +
    `I've also put this on your care team's <b>Needs attention</b> list for <b>Keisha Brown</b> (social worker) and <b>Marie Thibodeaux, RN</b> — they can see it now.<br><br>` +
    `I'm not going to try to talk you through this myself — a person should be with you for it.`; },
  urgent(){ return `<b>Call your care team now — don't wait for your next appointment.</b><br><br>` +
    `<b>Dr. Simone Peters</b> · Medical Oncologist, Ochsner Baton Rouge — oncology line, 24/7<br>` +
    `<b>Marie Thibodeaux, RN</b> · Patient Navigator<br><br>` +
    `If this feels severe — or if it's chest pain, trouble breathing, or you can't stay awake — call <b>911</b>.<br><br>` +
    `I won't guess at whether a symptom is serious. That's a call for your team, and they would much rather hear from you now than later.`; },
  clinical(){ return `<b>That's a question for your care team, and I won't guess at it.</b><br><br>` +
    `Medication and symptom decisions depend on your labs, your other prescriptions, and exactly where you are in the cycle — things only Dr. Peters and Marie can weigh.<br><br>` +
    `<b>Dr. Simone Peters</b> · Medical Oncologist, Ochsner Baton Rouge — oncology line, 24/7<br>` +
    `<b>Marie Thibodeaux, RN</b> · Patient Navigator<br><br>` +
    `If it feels urgent, call them now rather than waiting for the next visit.`; }
}

export const REMI_FALLBACK =
`I don't have that in your record, and I won't guess at it.<br><br>` +
  `Things I can answer: your diagnosis and stage, your plan, your next appointment or what's on any day, how you've been feeling, your device readings, rides, costs, support groups, and who's on your care team.<br><br>` +
  `For anything clinical, <b>Dr. Peters</b> and <b>Marie Thibodeaux, RN</b> are the ones to ask. Keisha (social worker) handles rides and money.`
